# Использование официального образа Python
FROM python:3.12-slim

# Установка переменных окружения
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Установка зависимостей системы
RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc libpq-dev gosu \
    && rm -rf /var/lib/apt/lists/*

# Создание рабочей директории
WORKDIR /app

# Копирование файла зависимостей
COPY requirements.txt /app/

# Установка зависимостей
RUN pip install --no-cache-dir -r requirements.txt

# Копирование кода проекта
COPY . /app/

# Создание непривилегированного пользователя
RUN addgroup --system app && adduser --system --group app

# Смена владельца файлов
RUN chown -R app:app /app

# Entrypoint-скрипт, чинящий права на volume перед стартом
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Сбор статических файлов Django
# RUN python manage.py collectstatic --noinput

# Открытие порта
EXPOSE 8000

ENTRYPOINT ["/entrypoint.sh"]

# Запуск Gunicorn
CMD ["daphne", "-b", "0.0.0.0", "-p", "8000", "frame_shop.asgi:application"]