# --- Стадия сборки ---
FROM node:20-alpine as builder

# Установка рабочей директории
WORKDIR /app/frontend

# Копирование package.json и package-lock.json
COPY frontend/package.json frontend/package-lock.json ./

# Установка зависимостей
RUN npm install

# Копирование остальных файлов фронтенда
COPY frontend/ ./

# Сборка приложения
RUN npm run build

# --- Стадия раздачи ---
FROM nginx:1.25-alpine

# Аргумент для выбора файла конфигурации Nginx
ARG NGINX_CONF=nginx/local.conf

# Удаление стандартной конфигурации nginx
RUN rm /etc/nginx/conf.d/default.conf

# Установка openssl для генерации сертификатов
RUN apk add --no-cache openssl

# Генерация самоподписанного SSL-сертификата (для локальной разработки)
RUN mkdir -p /etc/nginx/ssl && \
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/nginx/ssl/nginx-selfsigned.key \
    -out /etc/nginx/ssl/nginx-selfsigned.crt \
    -subj "/C=RU/ST=Moscow/L=Moscow/O=Dev/CN=localhost"

# Копирование нужной конфигурации nginx
COPY ${NGINX_CONF} /etc/nginx/conf.d/default.conf

# Копирование собранного фронтенда из стадии сборки
COPY --from=builder /app/frontend/dist /var/www/SHOP/frontend/dist

# Директории для статики/медиа Django (подключаются через volume из backend)
RUN mkdir -p /var/www/SHOP/staticfiles && mkdir -p /var/www/SHOP/media

# Открытие порта 80
EXPOSE 80

# Запуск Nginx
CMD ["nginx", "-g", "daemon off;"]