services:
  db:
    image: postgres:14-alpine
    container_name: shop_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: shop_backend
    volumes:
      - staticfiles:/app/staticfiles
      - media:/app/media
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DJANGO_DEBUG=${DJANGO_DEBUG:-True}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1,backend,0.0.0.0}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS:-http://localhost,https://localhost,http://127.0.0.1,https://127.0.0.1}
      - DB_ENGINE=django.db.backends.postgresql
      - DB_HOST=db
      - DB_PORT=5432
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: shop_frontend
    volumes:
      - staticfiles:/var/www/SHOP/staticfiles
      - media:/var/www/SHOP/media
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  staticfiles:
  media: