# Generated by Django 6.0.2 on 2026-09-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='discountusage',
            name='discounts_d_order_i_7a226f_idx',
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
