# Generated by Codex on 2026-09-17

from django.db import migrations, models


def mark_existing_orders_seen(apps, schema_editor):
    apps.get_model('orders', 'Order').objects.update(manager_seen=True)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='manager_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            mark_existing_orders_seen,
            migrations.RunPython.noop,
        ),
    ]
