# Generated by Django 6.0.2 on 2026-09-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_manager_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selected_attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
