# Generated by Django 6.0.2 on 2026-09-25 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_discount_total_order_subtotal_and_more'),
        ('shop', '0004_productvariant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shop.productvariant'),
        ),
    ]
